name: Backfire
main: xyz.nkomarn.Backfire.Backfire
version: 2.1
author: TechToolbox (@nkomarn)
description: A simple plugin to control the Fallback server.
api-version: 1.15

permissions:
  backfire.priority:
    description: "Gives a player premium priority in the queue."